/**
 * @file        exti.c
 * @brief       Tests EXTI peripheral modes (Single, Continuous)
 * @author      Marcos E. Mancia Jr.
 * @date        2026-06-30
 * @version     1.0
 */
#include "stm32f411xe.h"
#include "exti.h"
#include "uart.h"

/***** USEFUL MACROS *****/
#define GPIOAEN				(1U<<0)
#define GPIOCEN				(1U<<2)
#define SYSCFGEN			(1U<<14)

#define LINE13			(1U<<13)

/***** TEST FUNCTIONS *****/

/**
 * @brief       Tests External Interrupt functionality via on-board LED
 */
void exti_test(void) {
	/*Enable CLK access to GPIOA*/
	RCC->AHB1ENR |= GPIOAEN;

	/*Set PA5 (connected to on-board LED) as output pin*/
	GPIOA->MODER |= (1U<<10);
	GPIOA->MODER &= ~(1U<<11);

	/*Initialize necessary peripherals for test*/
	exti_init();
	uart2_tx_init();

	/*No loop code needed due to interrupt programming*/
	while(1) {}
}

/***** HELPER FUNCTIONS *****/

/**
 * @brief       Initializes EXTI13 on pin PC13
 */
void exti_init(void) {
	/*Disable global interrupt*/
	__disable_irq();

	/*Enable CLK access for GPIOC*/
	RCC->AHB1ENR |= GPIOCEN;

	/*Set PC13 as input*/
	GPIOC->MODER &= ~(1U<<26);
	GPIOC->MODER &= ~(1U<<27);

	/*Enable CLK access for SYSCFG*/
	RCC->APB2ENR |= SYSCFGEN;

	/*Select PORTC for EXTI13*/
	SYSCFG->EXTICR[3] |= (1U<<5);

	/*Unmask EXTI13*/
	EXTI->IMR |= (1U<<13);

	/*Select falling edge trigger*/
	EXTI->FTSR |= (1U<<13);

	/*Enable EXTI line in NVIC*/
	NVIC_EnableIRQ(EXTI15_10_IRQn);

	/*Enable global interrupt*/
	__enable_irq();
}

/**
 * @brief       Callback function executed when an EXTI13 event occurs that
 * 		        transmits a notification message via UART and toggles LED.
 */
static void exti_callback(void) {
	my_put("BTN Pressed... ");
	GPIOA->ODR ^= (1U<<5);
	my_put("Returning to main loop...\n\r");
}

/**
 * @brief       Interrupt Service Routine for EXTI lines 10 through 15 that
 * 		        checks if the interrupt was generated by line 13
 */
void EXTI15_10_IRQHandler(void) {
	if((EXTI->PR & LINE13)) {
		/*Clear PR flag*/
		EXTI->PR |= LINE13;

		exti_callback();
	}
}
